//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
)

func main() {
	templateFile, err := template.ParseFiles("index.html")
	if err != nil {
		panic(fmt.Errorf("parse index HTML template: %w", err))
	}
	script, err := os.ReadFile("../javascript/components/dark-light-toggle.js")
	if err != nil {
		panic(fmt.Errorf("read dark-light-toggle component: %w", err))
	}

	var generated bytes.Buffer
	data := struct {
		DarkLightToggleScript template.JS
	}{
		DarkLightToggleScript: template.JS(script),
	}
	if err := templateFile.Execute(&generated, data); err != nil {
		panic(fmt.Errorf("render index HTML template: %w", err))
	}
	if err := os.WriteFile("index.gen.html", generated.Bytes(), 0o644); err != nil {
		panic(fmt.Errorf("write generated index HTML: %w", err))
	}
}
